/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformArgs = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpResponse,
});

export const idlService = IDL.Service({
  'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getCompanionPreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'saveChatHistory' : IDL.Func([IDL.Vec(Message)], [], []),
  'saveCompanionPreference' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpResponse,
  });
  
  return IDL.Service({
    'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getCompanionPreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'saveChatHistory' : IDL.Func([IDL.Vec(Message)], [], []),
    'saveCompanionPreference' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func([TransformArgs], [HttpResponse], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };